version: "3.8"

services:
  bot:
    build: .
    container_name: sysalert-monitor-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - monitor-net
    healthcheck:
      test: ["CMD", "pgrep", "-f", "bot.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  monitor-net:
    driver: bridge