name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 mypy black
      
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
      
      - name: Type check
        run: |
          mypy --ignore-missing-imports bot.py db.py models.py
        continue-on-error: true
      
      - name: Run tests
        run: |
          pytest -v --tb=short
      
      - name: Check code formatting
        run: |
          black --check --line-length 120 .
        continue-on-error: true
  
  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: |
          docker build -t sysalert-monitor-bot:latest .
      
      - name: Test Docker image
        run: |
          docker run --rm sysalert-monitor-bot:latest python -c "import bot; print('OK')"
